API_V1_ROUTER_PREFIX = "/api/v1"

USER_PREFIX = "/user"
USER_CREATE_USER = "/create_user"
USER_LOGIN_USER = "/login_user"
USER_REFRESH_USER = "/refresh_user"
USER_LOGOUT_USER = "/logout_user"
USER_GET_USER_DETAIL = "/get_user_detail"
USER_UPDATE_USER_DETAIL = "/update_user_detail"
USER_UPDATE_USER_PASSWORD = "/update_user_password"
USER_DELETE_USER = "/delete_user"

ADMIN_PREFIX = "/admin"
ADMIN_GET_USERS = "/get_users"
ADMIN_UPDATE_USER_BOARD_PERMISSION = "/update_user_board_permission"
ADMIN_UPDATE_USER_IS_BANNED = "/update_user_is_banned"
ADMIN_CREATE_BOARD = "/create_board"
ADMIN_GET_BOARD = "/get_board"
ADMIN_GET_BOARDS = "/get_boards"
ADMIN_UPDATE_BOARD = "/update_board"
ADMIN_DELET_BOARD = "/delete_board"

AI_PREFIX = "/ai"
AI_TRAIN_AI = "/train_ai"
AI_GET_AI = "/get_ai"
AI_GET_AIS = "/get_ais"
AI_UPDATE_AI = "/update_ai"
AI_DELETE_AI = "/delete_ai"
AI_AI_INFER = "/ai_infer"
AI_GET_AILOG = "/get_ailog"
AI_GET_AILOGS = "/get_ailogs"
AI_UPDATE_AILOG = "/update_ailog"
AI_DELETE_AILOG = "/delete_ailog"

BOARD_PREFIX = "/board"
BOARD_CREATE_POST = "/create_post"
BOARD_GET_POST = "/get_post"
BOARD_GET_POSTS = "/get_posts"
BOARD_UPDATE_POST = "/update_post"
BOARD_DELETE_POST = "/delete_post"
BOARD_CREATE_COMMNET = "/create_comment"
BOARD_GET_COMMENT = "/get_comment"
BOARD_GET_COMMENTS = "/get_comments"
BOARD_UPDATE_COMMENT = "/update_comment"
BOARD_DELETE_COMMENT = "/delete_comment"

CHAT_PREFIX = "/chat"
CHAT_CREATE_CHATSESSION = "/create_chatsession"
CHAT_GET_CHATSESSION = "/get_chatsession"
CHAT_GET_CHATSESSIONS = "/get_chatsessions"
CHAT_UPDATE_CHATSESSION = "/update_chatsession"
CHAT_DELETE_CHATSESSION = "/delete_chatsession"
CHAT_CREATE_CHAT = "/create_chat"
CHAT_GET_CHATS = "/get_chats"
CHAT_UPDATE_CHAT = "/update_chat"
CHAT_DELETE_CHAT = "/delete_chat"
CHAT_WEBSOCKET = "/ws/chat/{chatting_room_id}/{user_id}"
